### ISSUE TITLE
Argon2 is unhappy

### ISSUE THREAD

**Issue by hanssv** [aeternity/aeproject#504] opened 2024-03-05 08:27 UTC
**Describe the bug**
Running tests after fresh install fails with `Error: Cannot find module './lib/binding/napi-v3/argon2.node'`

**To Reproduce**
1. Go to a fresh directory
2. Clone `aeternity/ae_zk_tools`
3. Run `npm install`
4. Run `npm run test` and see the error

```
Error: Cannot find module './lib/binding/napi-v3/argon2.node'
Require stack:
- /Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/argon2/node_modules/argon2/argon2.js
- /Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/argon2/node.js
- /Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js
- /Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/aeproject/.build/cjs/src/lib/utils.js
- /Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/aeproject/.build/cjs/src/lib/index.js
- /Users/hans/Quviq/Aeternity/ae_zk_tools/test/sophia_contract_tests.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/argon2/node_modules/argon2/argon2.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/argon2/node.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at webpackUniversalModuleDefinition (/Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:3:314)
    at Object.<anonymous> (/Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/aeproject/.build/cjs/src/lib/utils.js:32:20)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/hans/Quviq/Aeternity/ae_zk_tools/node_modules/@aeternity/aeproject/.build/cjs/src/lib/index.js:30:30)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at file:///Users/hans/Quviq/Aeternity/ae_zk_tools/test/sophia_contract_tests.js:3:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Expected behavior**
Test runs (well they will fail since docker is not started, but fail in the expected way).

**Screenshots**
No pretty pictures this time...

**Please tell us about your environment:**

  - Node Version: v18.14.0
  - Protocol Version: Ceres
  - Compiler version: not relevant it doesn't get that far
  - VM Version: fate3
  - SDK Version: v13.2.1
  - Python version: v3.11.7

**Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)
```
  "devDependencies": {
    "@aeternity/aepp-sdk": "^13.2.1",
    "@aeternity/aeproject": "^4.8.2",
    "chai": "^4.3.8",
    "mocha": "^10.2.0",
    "snarkjs": "^0.7.3",
    "web-worker": "1.2.0"
  }
```

**Comment by thepiwo** [comment] 2024-03-05 12:03
I tried to reproduce it with my colleagues apple silicon machine as well as on AWS graviton instances and everything is working flawless there.

I assume there is something incorrectly cached or otherwise problematic with your setup.

**Comment by dincho** [comment] 2024-03-07 07:20
Works for me too on M1 MAX and node 20.11.1

**Comment by thepiwo** [comment] 2024-04-23 07:10
lets close this for now

**Closed by thepiwo** 2024-04-23 07:10 UTC
Labels: bug
