### ISSUE TITLE
Aeproject test stuck at contract deploy

### ISSUE THREAD

**Issue by VitalJeevanjot** [aeternity/aeproject#427] opened 2022-08-09 01:31 UTC
**Describe the bug**
When I run our superhero trading card tests, Before 4.1.4, the 4.0.0-beta.6 was working fine. I did changed the getClient() method to getSdk() then after the first Failed contract deploy test passes, the second one stuck for a long time and didn't move forward from there.

**To Reproduce**
1. Go to [repo](https://github.com/VitalJeevanjot/multisig-presale-contract-aes).
2. Run `aeproject test` after doing essentials.

**Expected behavior**
I expected it to run all the tests successfully.

**Screenshots**
Nothing returns but you can check the console log where `hello1` & `hello2` will print then it will stuck.

**Please tell us about your environment:**

  - Node Version: v14.18.3
  - Protocol Version: 4.1.4
  - Compiler version: ~
  - VM Version: ~
  - SDK Version: ~
  - Python version: v3.7.5

**Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

**Comment by thepiwo** [comment] 2022-08-09 07:56
thanks for the bug report, it is related to the sdk, will do some debugging and then update here and create an issue for the sdk team

**Comment by thepiwo** [comment] 2022-08-09 08:21
they are aware of the issue, it's with a third party dependency, we are discussing how to resolve that right now https://github.com/aeternity/aepp-sdk-js/issues/1657

**Comment by thepiwo** [comment] 2022-08-09 09:36
@VitalJeevanjot the issue is now resolved, when you reinstall/update dependencies it should work

ensure that you are using the latest aeproject version
`aeproject init --update`

if that doesn't resolve it you need to update local dependencies manually as we had to downgrade one package
`npm update && npm install`

**Comment by VitalJeevanjot** [comment] 2022-08-09 20:49
Thanks @thepiwo

**Comment by thepiwo** [comment] 2022-08-10 06:36
@VitalJeevanjot can you close the issue if its resolved for you?

**Closed** 2022-08-11 02:46 UTC
Labels: bug
